In [62]:
import tensorflow as tf
from sklearn.datasets import load_diabetes

X_diab, y_diab = load_diabetes(return_X_y=True)

In [173]:
class Layer:
    def __init__(self, units, input_layer=False):
        self.input_layer = input_layer
        self.units = units
        self.activation = 'relu'

    @tf.function
    def activationFunction(self, z):
        if self.activation == "linear":
            return z

        if self.activation == "relu":
            return tf.maximum(z, tf.zeros(z.shape))

        if self.activation == "sigmoid":
            return 1 / (1 + tf.exp(-z))

    def _weightInit(self, input_size):
        self.w = tf.Variable(tf.random.normal((input_size, self.units), mean = 0, stddev = 1 / input_size, name = 'w'))
        self.bias = tf.Variable(tf.zeros((1, self.units)))

        return self.w, self.bias

    def _update_w(self, grad):
        self.w.assign_sub(0.01 * grad)

    def _update_b(self, grad):
        self.bias.assign_sub(0.01 * grad)

    @tf.function
    def __call__(self, X):
        return self.activationFunction(X @ self.w + self.bias)

In [172]:
a = tf.Variable(4.)

lst_1 = [4]

lst_1.append(a)

In [171]:
class DenseNetwork:
    def __init__(self, layers):
        self.layers = layers

        self.tr_vars = []

        for i in range(1, len(self.layers)):
            self.tr_vars.append(self.layers[i]._weightInit(self.layers[i - 1].units))

    def fit(self, X, y):
        X = tf.Variable(X, dtype="float32")
        y = tf.Variable(y, dtype="float32")
        
        with tf.GradientTape(persistent=True) as tape:
            loss = self.network(X, y)

        for _ in range(1000):    
            grads = tape.gradient(loss, self.tr_vars)
            for i, (w, b) in enumerate(grads):
                self.layers[i + 1]._update_w(w)
                self.layers[i + 1]._update_b(b)


        del tape

    def predict(self, X):
        X = tf.constant(X, dtype='float32')
        for layer in self.layers[1:]:
            X = layer(X)
        return X


    @tf.function
    def network(self, X, y):
        y_pred = self.forward(X)
        loss = tf.losses.mean_squared_error(y_pred, y)
        tf.print(loss)
        return loss

    @tf.function
    def forward(self, X):
        for layer in self.layers[1:]:
            X = layer(X)
        return X


In [174]:
nn = DenseNetwork([Layer(10), Layer(6), Layer(1)])

nn.fit(X_diab, y_diab)

nn.predict(X_diab)

[29074.4824 29070.3848 29074.4824 ... 29074.4824 29074.4824 29072.6094]


<tf.Tensor: shape=(442, 1), dtype=float32, numpy=
array([[1.7627767e+09],
       [1.7870652e+09],
       [1.7656493e+09],
       [1.7672520e+09],
       [1.7754961e+09],
       [1.7868820e+09],
       [1.7774844e+09],
       [1.7661069e+09],
       [1.7641581e+09],
       [1.7662835e+09],
       [1.7831983e+09],
       [1.7674548e+09],
       [1.7795535e+09],
       [1.7666308e+09],
       [1.7829354e+09],
       [1.7586022e+09],
       [1.7695528e+09],
       [1.7598433e+09],
       [1.7722161e+09],
       [1.7791845e+09],
       [1.7760262e+09],
       [1.7764138e+09],
       [1.7774031e+09],
       [1.7449309e+09],
       [1.7735917e+09],
       [1.7654292e+09],
       [1.7833943e+09],
       [1.7703052e+09],
       [1.7773303e+09],
       [1.7686304e+09],
       [1.7738540e+09],
       [1.7862948e+09],
       [1.7497883e+09],
       [1.7842511e+09],
       [1.7833718e+09],
       [1.7772212e+09],
       [1.7711073e+09],
       [1.7744639e+09],
       [1.7521760e+09],
       [1.7666

In [54]:
# import tensorflow.keras.datasets.mnist as tfds
# (x_train, y_train), (x_test, y_test) = tfds.load_data()

In [114]:
v = tf.Variable(1.0)

v.assign_sub(4.0)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=-3.0>

In [155]:
v = tf.Variable(1.0)
c = tf.Variable(2.0)
x = tf.constant(4.0)

@tf.function
def func(x):
    return x**2 * v

@tf.function
def func2(x):
   return func(x) ** 3 * c

with tf.GradientTape() as tape:
  result = func2(x)
  
tape.gradient(result, [(v, c),()])

[(<tf.Tensor: shape=(), dtype=float32, numpy=24576.0>,
  <tf.Tensor: shape=(), dtype=float32, numpy=4096.0>),
 <tf.Tensor: shape=(), dtype=float32, numpy=4096.0>]

In [143]:
a = tf.constant([4., 2., 3., 4., 5., 6.])
b = tf.constant([0., 2., 3., 4., 5., 6.])

tf.losses.mean_squared_error(a, b)

<tf.Tensor: shape=(), dtype=float32, numpy=2.6666667>